App type var
volterraedge/terraform-volterra-app-delivery-network pull request #22
Opened 2021-04-19 20:21 UTC by cohenaj194

closes https://github.com/volterraedge/terraform-volterra-app-delivery-network/issues/21

2021-04-21 23:42 UTC, madhukar32 requested changes
Can you please run terraform-docs, to update the Input variable in Readme

2021-04-21 23:43 UTC, madhukar32 commented
For terraform-docs, you can probably run this command

```
terraform-docs md tbl . >> README.md
```

2021-05-05 21:35 UTC, cohenaj194 reviewed
verified working in AC

now we just  need to fix the doc checks and this is gtg

2021-05-05 21:35 UTC, cohenaj194 commented on loadbalancer.tf
> +}
Do we need to add any `Application Type Features` to this app type?

2021-05-05 21:35 UTC, cohenaj194 commented on loadbalancer.tf
> +  }
`annotations` seemed to be the right choice here.  @madhukar32 should this be added under the `annotations` block or `labels` block?

2021-05-05 21:35 UTC, cohenaj194 commented on loadbalancer.tf
> +  }
@madhukar32 said we should use labels

2021-05-05 21:35 UTC, cohenaj194 commented on loadbalancer.tf
> +}
yes and added

2022-02-16 16:15 UTC, closed without merging